-- CreateTable
CREATE TABLE "resume" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,

    CONSTRAINT "resume_pkey" PRIMARY KEY ("id")
);
